language: swift
osx_image: xcode10.2

script: 
  - xcodebuild -project SupportEmail.xcodeproj -target SupportEmail -sdk iphonesimulator clean build
  - xcodebuild -project SupportEmail.xcodeproj -target Example -sdk iphonesimulator clean build
